<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUmqJr0Y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUmqJr0Y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUmqJr0Y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUmqJr0Y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUmqJr0Y\App_KernelDevDebugContainer([
    'container.build_hash' => 'UmqJr0Y',
    'container.build_id' => '714ba346',
    'container.build_time' => 1689581036,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUmqJr0Y');
