<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBe3ffRB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBe3ffRB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBe3ffRB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBe3ffRB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBe3ffRB\App_KernelDevDebugContainer([
    'container.build_hash' => 'Be3ffRB',
    'container.build_id' => 'd1271e44',
    'container.build_time' => 1688546650,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBe3ffRB');
